# Generated by Django 5.2.4 on 2025-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_trecker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipeingredient",
            name="user_id",
            field=models.BigIntegerField(
                db_index=True, default=0, verbose_name="Пользователь"
            ),
            preserve_default=False,
        ),
    ]
