# Generated by Django 5.2.4 on 2025-08-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_trecker", "0002_recipeingredient_user_id"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="unique_recipe_ingredient_basefood",
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="unique_recipe_ingredient_customfood",
        ),
        migrations.RemoveConstraint(
            model_name="recipeingredient",
            name="unique_recipe_ingredient_manual",
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("base_food__isnull", False)),
                fields=("user_id", "recipe", "base_food"),
                name="unique_recipe_ingredient_basefood",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("custom_food__isnull", False)),
                fields=("user_id", "recipe", "custom_food"),
                name="unique_recipe_ingredient_customfood",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipeingredient",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("base_food__isnull", True), ("custom_food__isnull", True)
                ),
                fields=(
                    "user_id",
                    "recipe",
                    "name",
                    "proteins",
                    "fats",
                    "carbohydrates",
                ),
                name="unique_recipe_ingredient_manual",
            ),
        ),
    ]
