# Generated by Django 5.2.4 on 2025-08-15 20:46

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "nutrition_trecker",
            "0003_remove_recipeingredient_unique_recipe_ingredient_basefood_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eatenfood",
            name="eatenfood_date_valid",
        ),
        migrations.AddConstraint(
            model_name="eatenfood",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("eaten_at__lte", django.db.models.functions.datetime.Now())
                ),
                name="eatenfood_date_valid",
            ),
        ),
    ]
