# Generated by Django 5.2.4 on 2026-04-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition_trecker", "0004_remove_eatenfood_eatenfood_date_valid_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="basefood",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Базовый продукт",
                "verbose_name_plural": "Базовые продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="customfood",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Пользовательский продукт",
                "verbose_name_plural": "Пользовательские продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="eatenfood",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Приём пищи",
                "verbose_name_plural": "Приёмы пищи",
            },
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
        migrations.AlterModelOptions(
            name="recipeingredient",
            options={"ordering": ["created_at"], "verbose_name": "Ингредиент"},
        ),
    ]
