server {
    listen 80;
    server_name localhost;

    location /static/ {
        alias /static/;
        expires 30d;
        add_header Cache-Control "public";
    }

    location /media/ {
        alias /media/;
        expires 30d;
        add_header Cache-Control "public";
    }

    # Всё остальное отдаём через gunicorn контейнер
    location / {
        proxy_pass http://nutrition:8001;  # имя контейнера Django и порт gunicorn
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}