# Generated by Django 5.2.4 on 2026-01-03 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Название базового упражнения",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Грудь"),
                            ("BACK", "Спина"),
                            ("SHOULDERS", "Плечи"),
                            ("BICEPS", "Бицепс"),
                            ("TRICEPS", "Трицепс"),
                            ("QUADS", "Квадрицепс"),
                            ("HAMSTRINGS", "Бицепс бедра"),
                            ("GLUTES", "Ягодицы"),
                            ("CALVES", "Икры"),
                            ("ABS", "Пресс"),
                            ("FOREARMS", "Предплечья"),
                            ("FULL_BODY", "Все тело"),
                            ("CORE", "Кор"),
                        ],
                        help_text="Основная целевая группа мышц",
                        max_length=20,
                        verbose_name="Основная группа мышц",
                    ),
                ),
                (
                    "secondary_muscle_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHEST", "Грудь"),
                            ("BACK", "Спина"),
                            ("SHOULDERS", "Плечи"),
                            ("BICEPS", "Бицепс"),
                            ("TRICEPS", "Трицепс"),
                            ("QUADS", "Квадрицепс"),
                            ("HAMSTRINGS", "Бицепс бедра"),
                            ("GLUTES", "Ягодицы"),
                            ("CALVES", "Икры"),
                            ("ABS", "Пресс"),
                            ("FOREARMS", "Предплечья"),
                            ("FULL_BODY", "Все тело"),
                            ("CORE", "Кор"),
                        ],
                        help_text="Вторичная группа мышц, которая также работает",
                        max_length=20,
                        null=True,
                        verbose_name="Дополнительная группа мышц",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Силовое"),
                            ("CARDIO", "Кардио"),
                            ("STRETCHING", "Растяжка"),
                            ("MOBILITY", "Мобильность"),
                            ("BALANCE", "Баланс"),
                            ("PLYOMETRIC", "Плиометрика"),
                        ],
                        help_text="Тип физической активности",
                        max_length=15,
                        verbose_name="Вид упражнения",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание техники выполнения",
                        null=True,
                        verbose_name="Описание техники",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Фотография упражнения",
                        upload_to="photos/base_exercises/",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Базовое упражнение",
                "verbose_name_plural": "Базовые упражнения",
            },
        ),
        migrations.CreateModel(
            name="CustomExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Название базового упражнения",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "primary_muscle_group",
                    models.CharField(
                        choices=[
                            ("CHEST", "Грудь"),
                            ("BACK", "Спина"),
                            ("SHOULDERS", "Плечи"),
                            ("BICEPS", "Бицепс"),
                            ("TRICEPS", "Трицепс"),
                            ("QUADS", "Квадрицепс"),
                            ("HAMSTRINGS", "Бицепс бедра"),
                            ("GLUTES", "Ягодицы"),
                            ("CALVES", "Икры"),
                            ("ABS", "Пресс"),
                            ("FOREARMS", "Предплечья"),
                            ("FULL_BODY", "Все тело"),
                            ("CORE", "Кор"),
                        ],
                        help_text="Основная целевая группа мышц",
                        max_length=20,
                        verbose_name="Основная группа мышц",
                    ),
                ),
                (
                    "secondary_muscle_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHEST", "Грудь"),
                            ("BACK", "Спина"),
                            ("SHOULDERS", "Плечи"),
                            ("BICEPS", "Бицепс"),
                            ("TRICEPS", "Трицепс"),
                            ("QUADS", "Квадрицепс"),
                            ("HAMSTRINGS", "Бицепс бедра"),
                            ("GLUTES", "Ягодицы"),
                            ("CALVES", "Икры"),
                            ("ABS", "Пресс"),
                            ("FOREARMS", "Предплечья"),
                            ("FULL_BODY", "Все тело"),
                            ("CORE", "Кор"),
                        ],
                        help_text="Вторичная группа мышц, которая также работает",
                        max_length=20,
                        null=True,
                        verbose_name="Дополнительная группа мышц",
                    ),
                ),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("STRENGTH", "Силовое"),
                            ("CARDIO", "Кардио"),
                            ("STRETCHING", "Растяжка"),
                            ("MOBILITY", "Мобильность"),
                            ("BALANCE", "Баланс"),
                            ("PLYOMETRIC", "Плиометрика"),
                        ],
                        help_text="Тип физической активности",
                        max_length=15,
                        verbose_name="Вид упражнения",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание техники выполнения",
                        null=True,
                        verbose_name="Описание техники",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Фотография упражнения",
                        null=True,
                        upload_to="photos/custom_exercises/",
                        verbose_name="Фото",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кастомное упражнение",
                "verbose_name_plural": "Кастомные упражнения",
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Дата и время тренировки",
                        verbose_name="Дата и время",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Длительность тренировки в минутах",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="Длительность (минуты)",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Название тренировки",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Подробное описание тренировки",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["-date_time"],
                "indexes": [
                    models.Index(
                        fields=["user_id", "date_time"],
                        name="training_tr_user_id_403dca_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CompletedExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                ("user_id", models.BigIntegerField(db_index=True)),
                (
                    "base_exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.baseexercise",
                    ),
                ),
                (
                    "custom_exercise",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="training.customexercise",
                    ),
                ),
                (
                    "training_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="training.trainingsession",
                        verbose_name="Упражнение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполненное упражнение",
                "verbose_name_plural": "Выполненные упражнения",
                "ordering": ["training_session", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "repetitions",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Количество повторений в подходе",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Повторения",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Вес снаряда в килограммах",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Время выполнения подхода в секундах",
                        null=True,
                        verbose_name="Время выполнения (сек)",
                    ),
                ),
                (
                    "distance_meters",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Пройденная дистанция в метрах",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Дистанция (м)",
                    ),
                ),
                (
                    "rest_after_set",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Время отдыха после подхода в секундах",
                        verbose_name="Отдых после подхода (сек)",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Порядковый номер подхода (1, 2, 3...)",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер подхода",
                    ),
                ),
                (
                    "completed_exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercise_set",
                        to="training.completedexercise",
                        verbose_name="Подход",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выполненный подход",
                "verbose_name_plural": "Выполненные подходы",
                "ordering": ["completed_exercise", "set_number"],
                "indexes": [
                    models.Index(
                        fields=["completed_exercise"],
                        name="training_ex_complet_934e5b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="completedexercise",
            index=models.Index(
                fields=["user_id", "training_session"],
                name="training_co_user_id_ae9ce0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="completedexercise",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("custom_exercise__isnull", False),
                        ("base_exercise__isnull", True),
                    ),
                    models.Q(
                        ("custom_exercise__isnull", True),
                        ("base_exercise__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="completed_exercise_has_valid_source",
            ),
        ),
    ]
