# Generated by Django 5.2.4 on 2026-01-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_completedexercise_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customexercise",
            name="user_id",
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="customexercise",
            index=models.Index(
                fields=["user_id", "name"], name="training_cu_user_id_9c0f54_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customexercise",
            constraint=models.UniqueConstraint(
                fields=("user_id", "name"), name="unique_customexercise_per_user"
            ),
        ),
    ]
