# Generated by Django 5.2.4 on 2026-01-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0003_customexercise_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseset",
            name="user_id",
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
