# Generated by Django 5.2.4 on 2026-01-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0004_exerciseset_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customexercise",
            name="image",
        ),
    ]
