# Generated by Django 5.2.4 on 2026-01-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_remove_customexercise_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseexercise",
            name="image_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="photos/base_exercises/thumbs/",
            ),
        ),
    ]
