# Generated by Django 5.2.4 on 2026-01-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_baseexercise_image_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseexercise",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Без оборудования"),
                    ("BARBELL", "Штанга"),
                    ("DUMBBELL", "Гантели"),
                    ("KETTLEBELL", "Гиря"),
                    ("RESISTANCE_BAND", "Резина"),
                    ("MACHINE", "Тренажер"),
                    ("CABLE", "Тросовый тренажер"),
                    ("MEDICINE_BALL", "Медбол"),
                    ("STABILITY_BALL", "Фитбол"),
                    ("TRX", "TRX"),
                    ("JUMP_ROPE", "Скакалка"),
                    ("PULL_UP_BAR", "Турник"),
                    ("DIP_BAR", "Брусья"),
                    ("BOX", "Короб"),
                ],
                default=0,
                help_text="Тип требуемого тренировочного оборудования",
                max_length=20,
                verbose_name="Оборудование",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customexercise",
            name="equipment_type",
            field=models.CharField(
                choices=[
                    ("NONE", "Без оборудования"),
                    ("BARBELL", "Штанга"),
                    ("DUMBBELL", "Гантели"),
                    ("KETTLEBELL", "Гиря"),
                    ("RESISTANCE_BAND", "Резина"),
                    ("MACHINE", "Тренажер"),
                    ("CABLE", "Тросовый тренажер"),
                    ("MEDICINE_BALL", "Медбол"),
                    ("STABILITY_BALL", "Фитбол"),
                    ("TRX", "TRX"),
                    ("JUMP_ROPE", "Скакалка"),
                    ("PULL_UP_BAR", "Турник"),
                    ("DIP_BAR", "Брусья"),
                    ("BOX", "Короб"),
                ],
                default=0,
                help_text="Тип требуемого тренировочного оборудования",
                max_length=20,
                verbose_name="Оборудование",
            ),
            preserve_default=False,
        ),
    ]
