# Generated by Django 5.2.4 on 2026-01-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0007_baseexercise_equipment_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exerciseset",
            options={
                "ordering": ["completed_exercise", "created_at"],
                "verbose_name": "Выполненный подход",
                "verbose_name_plural": "Выполненные подходы",
            },
        ),
        migrations.RemoveField(
            model_name="exerciseset",
            name="set_number",
        ),
    ]
