# Generated by Django 5.2.4 on 2026-01-16 16:52

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0008_alter_exerciseset_options_and_more"),
    ]

    operations = [
        TrigramExtension(),
    ]
