# Generated by Django 5.2.4 on 2026-01-16 18:06

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0009_auto_20260116_1952"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customexercise",
            name="training_cu_user_id_9c0f54_idx",
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="completed_exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="training.completedexercise",
                verbose_name="Подход",
            ),
        ),
        migrations.AddIndex(
            model_name="baseexercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="base_ex_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="customexercise",
            index=models.Index(
                fields=["user_id"], name="training_cu_user_id_c32bfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customexercise",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="custom_ex_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="trainingsession",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name", "description"],
                name="training_session_name_trgm_idx",
                opclasses=["gin_trgm_ops", "gin_trgm_ops"],
            ),
        ),
    ]
