# Generated by Django 5.2.4 on 2026-03-11 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "training",
            "0010_remove_customexercise_training_cu_user_id_9c0f54_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseexercise",
            options={
                "ordering": ["name"],
                "verbose_name": "Базовое упражнение",
                "verbose_name_plural": "Базовые упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="trainingsession",
            options={
                "ordering": ["date_time"],
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
            },
        ),
        migrations.AlterField(
            model_name="exerciseset",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Вес снаряда в килограммах",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Вес (кг)",
            ),
        ),
    ]
