# Generated by Django 5.2.4 on 2026-04-21 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0011_alter_baseexercise_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customexercise",
            options={
                "ordering": ["name"],
                "verbose_name": "Кастомное упражнение",
                "verbose_name_plural": "Кастомные упражнения",
            },
        ),
    ]
