# Generated by Django 5.2.4 on 2026-04-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the object was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date when the object was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID пользователя",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Мужчина"), ("F", "Женщина")],
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Дата рождения")),
                ("height", models.PositiveSmallIntegerField(verbose_name="Рост (см)")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Вес (кг)"
                    ),
                ),
                (
                    "body_fat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="% жира",
                    ),
                ),
                (
                    "activity_level",
                    models.FloatField(
                        choices=[
                            (1.2, "Сидячий"),
                            (1.375, "Легкий (1-3 тренировки/нед)"),
                            (1.55, "Средний (3-5 тренировок/нед)"),
                            (1.725, "Высокий (6-7 тренировок/нед)"),
                            (1.9, "Экстремальный"),
                        ],
                        default=1.2,
                        verbose_name="Активность",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("CUT", "Похудение"),
                            ("MAINTAIN", "Поддержание"),
                            ("BULK", "Набор массы"),
                        ],
                        default="MAINTAIN",
                        max_length=10,
                        verbose_name="Цель",
                    ),
                ),
                (
                    "target_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Целевой вес",
                    ),
                ),
                (
                    "target_proteins",
                    models.PositiveSmallIntegerField(verbose_name="Цель белки (г)"),
                ),
                (
                    "target_fats",
                    models.PositiveSmallIntegerField(verbose_name="Цель жиры (г)"),
                ),
                (
                    "target_carbs",
                    models.PositiveSmallIntegerField(verbose_name="Цель углеводы (г)"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(blank=True, verbose_name="Пищевые ограничения"),
                ),
            ],
            options={
                "verbose_name": "Профиль пользователя",
                "verbose_name_plural": "Профили пользователей",
            },
        ),
    ]
