# Generated by Django 5.2.4 on 2026-04-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={},
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="target_weight",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="activity_level",
            field=models.FloatField(
                choices=[
                    (1.2, "Сидячий"),
                    (1.375, "Легкий (1-3 тренировки/нед)"),
                    (1.55, "Средний (3-5 тренировок/нед)"),
                    (1.725, "Высокий (6-7 тренировок/нед)"),
                    (1.9, "Экстремальный"),
                ],
                default=1.2,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="body_fat",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Мужчина"), ("F", "Женщина")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("CUT", "Похудение"),
                    ("MAINTAIN", "Поддержание"),
                    ("BULK", "Набор массы"),
                ],
                default="MAINTAIN",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="height",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_carbs",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_fats",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_proteins",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user_id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="weight",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
