# Generated by Django 5.2.4 on 2026-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="target_weight",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
